### ISSUE TITLE
Possible typo in readme install

### ISSUE THREAD

**Issue by dr-dos** [bgentry/dymo_render#14]
Hello,

Thanks for releasing this project. At the install stage I could not get 

``
gem "dymo_render"
``
 to work, but I was able to install the package with:
``
gem install dymo_render
``
and now: 
`` 
gem list
``
includes dymo_render.  

I am not very familiar with ruby but I hope this is useful.

**Comment by bgentry** [comment]
Ah, that line is something you'd have to put in your `Gemfile` to use bundler, which is the normal way for installing dependencies in Ruby. Good luck!
